name: Build, Sign, and Publish Artifact

on:
  push:
    branches:
      - main

jobs:
  build-sign-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup OpenSSL
        run: |
          openssl version

      - name: Generate RSA Key Pair
        run: |
          openssl genpkey -algorithm RSA -out private_key.pem -pkeyopt rsa_keygen_bits:2048
          openssl rsa -in private_key.pem -pubout -out public_key.pem

      - name: Build artifact (tar.gz)
        run: |
          tar -czf artifact.tar.gz .

      - name: Sign artifact with private key
        run: |
          openssl dgst -sha256 -sign private_key.pem -out artifact.tar.gz.sig artifact.tar.gz

      - name: Upload artifact and signature
        uses: actions/upload-artifact@v4
        with:
          name: artifact-package
          path: |
            artifact.tar.gz
            artifact.tar.gz.sig

      - name: Upload public key for Jenkins
        uses: actions/upload-artifact@v4
        with:
          name: public-key
          path: public_key.pem
