name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '24 5 * * 5'

jobs:
  analyze:
    name: Analyze (${{ matrix.language }})
    # For Swift, use macOS; for other languages, use Ubuntu.
    runs-on: ${{ (matrix.language == 'swift' && 'macos-latest') || 'ubuntu-latest' }}
    permissions:
      security-events: write  # required for CodeQL
      packages: read          # to fetch internal or private CodeQL packs
      actions: read           # (only required for private repositories)
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - language: actions
            build-mode: none
          - language: javascript-typescript
            build-mode: none
          # Add additional languages as needed.
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          # Use a writable directory under the workspace
          db-location: "${{ github.workspace }}/my_codeql_db"
          languages: ${{ matrix.language }}
          build-mode: ${{ matrix.build-mode }}
          # Optionally, specify custom queries:
          # queries: security-extended,security-and-quality

      - if: matrix.build-mode == 'manual'
        name: Run manual build steps
        shell: bash
        run: |
          echo 'Running manual build steps'
          # Insert your custom build steps here.
          exit 1

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{ matrix.language }}"

      - name: Export SARIF from CodeQL Database
        if: always()
        run: |
          echo "Exporting CodeQL diagnostics..."
          codeql database export-diagnostics "${{ github.workspace }}/my_codeql_db" \
            --format=sarif-latest \
            --output=codeql-results.sarif \
            --sarif-include-diagnostics

      - name: Upload CodeQL (SAST) Results Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          # Parameterize artifact name by language to avoid conflicts.
          name: sast-results-${{ matrix.language }}
          path: codeql-results.sarif

      # Optional: Also upload the CodeQL database directory as an artifact.
      - name: Upload CodeQL Database Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: codeql-database-${{ matrix.language }}
          path: "${{ github.workspace }}/my_codeql_db"

  build:
    name: Build and Save Docker Image
    runs-on: ubuntu-latest
    # This job depends on the analysis job. Remove or adjust "needs" if you wish to run concurrently.
    needs: analyze
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image for archon-demo-node-app
        run: docker build . -t archon-demo-node-app:latest

      - name: Save Docker image to TAR file
        run: docker save archon-demo-node-app:latest -o archon-demo-node-app.tar

      - name: Upload TAR artifact
        uses: actions/upload-artifact@v4.1.0
        with:
          name: docker-image-tar
          path: archon-demo-node-app.tar