name: CI with Custom OpenSSL Attestation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '24 5 * * 5'
  workflow_dispatch:
    inputs:
      override_security_check:
        description: 'Override security check failures and proceed with build'
        type: boolean
        default: false

jobs:
  bootstrap-secrets:
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.bootstrap == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Authenticate GH CLI
        env:
          GH_TOKEN: ${{ secrets.GH_ADMIN_TOKEN }}
        run: |
          echo "$GH_TOKEN" | gh auth login --with-token

      - name: Generate RSA Keypair
        run: |
          openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 -out private_key.pem
          openssl pkey -in private_key.pem -pubout -out public_key.pem

      - name: Compute expected hash
        run: |
          docker build . -t tmp-image:latest
          docker save tmp-image:latest -o image.tar
          sha256sum image.tar | cut -d' ' -f1 > expected.sha256

      - name: Publish PRIVATE_KEY_PEM secret
        run: |
          gh secret set PRIVATE_KEY_PEM --body-file private_key.pem

      - name: Publish PUBLIC_KEY_PEM secret
        run: |
          gh secret set PUBLIC_KEY_PEM --body-file public_key.pem

      - name: Publish EXPECTED_HASH secret
        run: |
          gh secret set EXPECTED_HASH --body-file expected.sha256
    
