name: Test sigstore

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '24 5 * * 5'
  workflow_dispatch:
    inputs:
      override_security_check:
        description: 'Override security check failures and proceed with build'
        type: boolean
        default: false

jobs:
  sign:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Write encrypted key
        run: |
          printf '%s\n' "${{ secrets.PRIVATE_KEY_PEM }}" > cosign.key
      
      - name: Debug show cosign.key contents
        run: |
          echo "## cosign.key (first 5 lines) ##"
          head -n5 cosign.key | sed -e 's/$/↵/'   # ↵ makes line endings visible
          echo "## total lines: ##"
          wc -l cosign.key

      # 2) Strip off AES‑256 encryption into a plain PKCS#8 file
      - name: Decrypt cosign.key
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        run: |
          openssl pkcs8 \
            -inform PEM \
            -in cosign.key \
            -passin pass:"$COSIGN_PASSWORD" \
            -nocrypt \
            -out cosign.plain.key

      # [Optional] debug: verify it’s now an unencrypted P‑256 key
      - name: Inspect decrypted key
        run: |
          openssl pkey -in cosign.plain.key -text -noout

      # 3) Sign the image
      - name: Sign image
        run: |
          cosign sign \
            --key cosign.plain.key \
            ghcr.io/${{ env.REPO_OWNER }}/archon-demo-node-app:latest
